<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "anhlienquan".
 *
 * @property int $id
 * @property string|null $File
 * @property int|null $BaiViet_id
 * @property string|null $Alt
 * @property string|null $Title
 *
 * @property Baiviet $baiViet
 */
class AnhLienQuan extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'anhlienquan';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['BaiViet_id'], 'integer'],
            [['File', 'Alt', 'Title'], 'string', 'max' => 200],
            [['BaiViet_id'], 'exist', 'skipOnError' => true, 'targetClass' => Baiviet::className(), 'targetAttribute' => ['BaiViet_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'File' => 'File',
            'BaiViet_id' => 'Bai Viet ID',
            'Alt' => 'Alt',
            'Title' => 'Title',
        ];
    }

    /**
     * Gets query for [[BaiViet]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getBaiViet()
    {
        return $this->hasOne(BaiViet::className(), ['id' => 'BaiViet_id']);
    }
    public function beforeDelete()
    {
        $path = dirname(dirname(__DIR__)) . '/images/anhlienquan/'.$this->File;
        if(is_file($path)) unlink($path);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
