<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "capcongnhan".
 *
 * @property int $id
 * @property string|null $TenCapCongNhan
 * @property string|null $MoTa
 * @property string|null $Code
 *
 * @property Diadanh[] $diadanhs
 * @property Langnghe[] $langnghes
 */
class CapCongNhan extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'capcongnhan';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['MoTa'], 'string'],
            [['TenCapCongNhan'], 'required','message'=>'Tên cấp công nhận không được để trống'],
            [['MoTa'], 'required','message'=>'Mô tả không được để trống'],
            [['TenCapCongNhan', 'Code'], 'string', 'max' => 200],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'TenCapCongNhan' => 'Tên cấp công nhận',
            'MoTa' => 'Mô tả',
            'Code' => 'Code',
        ];
    }

    /**
     * Gets query for [[Diadanhs]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDiadanhs()
    {
        return $this->hasMany(DiaDanh::className(), ['CapCongNhan_id' => 'id']);
    }

    /**
     * Gets query for [[Langnghes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getLangnghes()
    {
        return $this->hasMany(LangNghe::className(), ['CapCongNhan_id' => 'id']);
    }
    public function beforeSave($insert)
    {
        $this->Code=API_H17::createCode($this->TenCapCongNhan);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
