<?php

namespace common\models;

use Yii;
use yii\db\Exception;
use yii\helpers\VarDumper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "langnghe".
 *
 * @property int $id
 * @property string|null $TenLangNghe
 * @property string|null $TomTat
 * @property string|null $MoTaChiTiet
 * @property string|null $AnhDaiDien
 * @property int $QuanHuyen_id
 * @property string|null $ToaDo
 * @property string|null $Code
 * @property int $CapCongNhan_id
 * @property string|null $Alt
 * @property string|null $Title
 *
 * @property BaiViet[] $baiviets
 * @property CapCongNhan $capCongNhan
 * @property QuanHuyen $quanHuyen
 */
class LangNghe extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public $anh_dai_dien;
    public static function tableName()
    {
        return 'langnghe';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['TomTat', 'MoTaChiTiet'], 'string'],
            [['QuanHuyen_id', 'CapCongNhan_id'], 'required'],
            [['QuanHuyen_id', 'CapCongNhan_id'], 'integer'],
            [['TenLangNghe', 'Code', 'Alt', 'Title'], 'string', 'max' => 200],
            [['AnhDaiDien'], 'string', 'max' => 250],
            [['ToaDo'], 'string', 'max' => 100],
            [['anh_dai_dien'], 'safe'],
            [['CapCongNhan_id'], 'exist', 'skipOnError' => true, 'targetClass' => CapCongNhan::className(), 'targetAttribute' => ['CapCongNhan_id' => 'id']],
            [['QuanHuyen_id'], 'exist', 'skipOnError' => true, 'targetClass' => QuanHuyen::className(), 'targetAttribute' => ['QuanHuyen_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'TenLangNghe' => 'Tên làng nghề',
            'TomTat' => 'Tóm tắt',
            'MoTaChiTiet' => 'Mô tả chi tiết',
            'AnhDaiDien' => 'Ảnh đại diện',
            'QuanHuyen_id' => 'Quận huyện',
            'ToaDo' => 'Tọa độ',
            'Code' => 'Code',
            'CapCongNhan_id' => 'Cấp công nhận',
            'Alt' => 'Alt',
            'Title' => 'Title',
            'anh_dai_dien' => 'Ảnh đại diện',
        ];
    }

    /**
     * Gets query for [[Baiviets]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getBaiviets()
    {
        return $this->hasMany(BaiViet::className(), ['LangNghe_id' => 'id']);
    }

    /**
     * Gets query for [[CapCongNhan]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCapCongNhan()
    {
        return $this->hasOne(CapCongNhan::className(), ['id' => 'CapCongNhan_id']);
    }

    /**
     * Gets query for [[QuanHuyen]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getQuanHuyen()
    {
        return $this->hasOne(QuanHuyen::className(), ['id' => 'QuanHuyen_id']);
    }
    public function beforeSave($insert)
    {
        $this->TenLangNghe=trim($this->TenLangNghe);
        $this->Code=API_H17::createCode($this->TenLangNghe);
        $anhdaidien=UploadedFile::getInstance($this,'anh_dai_dien');
        if($anhdaidien!=null){
            if(!$insert){
                $langnghe_old=LangNghe::findOne($this->id);
                try {
                    $path=dirname(dirname(__DIR__)) . '/images/anhdaidien/' . $langnghe_old->AnhDaiDien;
                    if(is_file($path)) unlink($path);
                }
                catch (Exception $ex){}
            }
            $file_type=API_H17::GetImageType($anhdaidien->type);
            $filename=$this->Code.time().$file_type;
            if(strlen($filename)>200) $filename = substr($filename,strlen($filename) - 200);
            $path=dirname(dirname(__DIR__)) . '/images/anhdaidien/' . $filename;
            $anhdaidien->saveAs($path);
            if(strpos(strtolower($file_type),'jpg')||strpos(strtolower($file_type),'jpeg')){
                $image=API_H17::cropImageJPG($path,1080,800);
                imagejpeg($image, $path);
            }
            elseif (strpos(strtolower($file_type),'png')){
                $image=API_H17::cropImagePNG($path,1080,800);
                imagepng($image,$path);
            }
            $this->AnhDaiDien=$filename;
            if(trim($this->Title)=='')  $this->Title=$this->TenLangNghe;
            if(trim($this->Alt)=='')  $this->Alt=$this->TenLangNghe;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function beforeDelete()
    {
        BaiViet::deleteAll(['LangNghe_id'=>$this->id]);
        yii::$app->session->setFlash('langnghe_delete_anhdaidien',$this->AnhDaiDien);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
    public function afterDelete()
    {
        $filename=yii::$app->session->getFlash('langnghe_delete_anhdaidien');
        yii::$app->session->removeFlash('langnghe_delete_anhdaidien');
        $path=dirname(dirname(__DIR__)) . '/images/anhdaidien/' . $filename;
        if(is_file($path)) unlink($path);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}
