<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "quanhuyen".
 *
 * @property int $id
 * @property string $TenQuanHuyen
 * @property string $Code
 *
 * @property DiaDanh[] $diadanhs
 * @property LangNghe[] $langnghes
 */
class QuanHuyen extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'quanhuyen';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['TenQuanHuyen'], 'required'],
            [['TenQuanHuyen', 'Code'], 'string', 'max' => 50],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'TenQuanHuyen' => 'Tên quận huyện',
            'Code' => 'Code',
        ];
    }

    /**
     * Gets query for [[Diadanhs]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDiadanhs()
    {
        return $this->hasMany(DiaDanh::className(), ['QuanHuyen_id' => 'id']);
    }

    /**
     * Gets query for [[Langnghes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getLangnghes()
    {
        return $this->hasMany(LangNghe::className(), ['QuanHuyen_id' => 'id']);
    }
    public function beforeSave($insert)
    {
        $this->TenQuanHuyen=trim($this->TenQuanHuyen);

        $this->Code = API_H17::createCode($this->TenQuanHuyen);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public  function  beforeDelete()
    {
        DiaDanh::deleteAll(['QuanHuyen_id' => 'id']);
        LangNghe::deleteAll(['QuanHuyen_id' => 'id']);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
